name: "Disk cleanup"
description: "Removes unused software to free disk space."

runs:
  using: composite
  steps:
    - name: Disk space before
      shell: bash
      run: df / -h
    - name: Disk cleanup
      shell: bash
      run: |
          sudo apt remove --purge -y -qqq \
              dotnet* \
              mono* \
              php* \
              clang*

          sudo apt autoremove --purge -y
          sudo apt autoclean -y

          sudo rm -rf \
              /usr/share/dotnet \
              /usr/share/php* \
              /usr/share/swift \
              /usr/share/miniconda \
              /usr/share/gradle* \
              /usr/local/lib/android \
              /usr/local/lib/mono* \
              /usr/local/lib/firefox \
              /usr/local/lib/node_modules
    - name: Disk space after
      shell: bash
      run: df / -h
