name: Build and deploy container apps images

on:
  workflow_call:
    inputs:
      keys:
        required: true
        type: string
        description: List of keys into `object` input
      object:
        required: true
        type: string
        description: JSON object of images to build and push
      resource-group:
        required: true
        type: string
        description: Which resource group to deploy to
      container-app-env-name:
        required: true
        type: string
        description: Name of the container apps env to deploy to

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo "${{ inputs.keys }}" | xargs -I {} printf '{}","' >> temp
          truncate -s-3 temp
          echo "value=[\"$(cat temp)\"]" >> $GITHUB_OUTPUT

  build-and-deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: [ setup-matrix ]
    strategy:
      matrix:
        value: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
        # See related issues
        # https://github.com/docker/build-push-action/issues/761#issuecomment-1575006515
        # https://github.com/moby/buildkit/issues/3969
        with:
          driver-opts: |
            image=moby/buildkit:v0.11.6
            network=host
      - uses: docker/login-action@v2
        with:
          registry: ${{ fromJson(inputs.object)[matrix.value]['registry'] }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: ${{ fromJson(inputs.object)[matrix.value]['dockerfile'] }}
          tags: ${{ fromJson(inputs.object)[matrix.value]['registry'] }}:${{ github.sha }}
          secrets: |
            git-credentials=${{ secrets.CLOUDSMITH_GIT_API_KEY }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy container app
        uses: azure/container-apps-deploy-action@v1
        with:
         containerAppName: ${{ fromJson(inputs.object)[matrix.value]['container-app-name'] }}
         containerAppEnvironment: ${{ inputs.container-app-env-name }}
         resourceGroup: ${{ inputs.resource-group }}
         imageToDeploy: ${{ fromJson(inputs.object)[matrix.value]['registry'] }}:${{ github.sha }}

