name: Docker build and push images

on:
  workflow_call:
    inputs:
      keys:
        required: true
        type: string
        description: List of keys into `object` input
      object:
        required: true
        type: string
        description: JSON object of images to build and push
      aks-repo:
        required: false
        type: string
        description: Aks repository to update image tags
      should_push:
        required: false
        type: boolean
        description: Wether to push to the registry or not
        default: true
      tag:
        required: false
        type: string
        description: Tag to set for all built images

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo "${{ inputs.keys }}" | xargs -I {} printf '{}","' >> temp
          truncate -s-3 temp
          echo "value=[\"$(cat temp)\"]" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: [ setup-matrix ]
    strategy:
      matrix:
        value: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ fromJson(inputs.object)[matrix.value]['registry'] }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ inputs.should_push }}
          file: ${{ fromJson(inputs.object)[matrix.value]['dockerfile'] }}
          tags: ${{ fromJson(inputs.object)[matrix.value]['registry'] }}:${{ inputs.tag || github.sha }}
          secrets: |
            git-credentials=${{ secrets.CLOUDSMITH_GIT_API_KEY }}

  update-tags:
    if: ${{ inputs.aks-repo }}
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.aks-repo }}
          token: ${{ secrets.CI_PAT_TOKEN }}
      - name: Install jq
        run: sudo apt install -y jq
      - uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "4.5.7"
      - name: Update tags
        run: |
          echo '${{ inputs.object }}' > object.json
          for key in $(jq -r 'keys[]' object.json); do
            REGISTRY=$(jq -r --arg KEY $key '.[$KEY].registry' object.json)
            cd $(jq -r --arg KEY $key '.[$KEY]."aks-path"' object.json)
            kustomize edit set image $REGISTRY:${{ github.sha }}
            cd -
          done
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT_TOKEN }}
        run: |
          git checkout -b ${{ github.event.repository.name }}-${{ github.sha }}
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git commit -am "Update ${{ github.event.repository.name }} image tags"
          git push -u origin HEAD
          gh pr create -B master -H ${{ github.event.repository.name }}-${{ github.sha }} --title 'Merge ${{ github.event.repository.name }}-tag-update' --body 'Created by Github action'
