name: Build npm cache

on:
  workflow_call:
    inputs:
      src-dir:
        type: string
        required: false
        default: .
        description: Path to source code

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ format('{0}/node_modules', inputs.src-dir) }}
          key: ${{ runner.os }}-${{ hashFiles(format('{0}/package*.json', inputs.src-dir)) }}
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ${{ inputs.src-dir }}
          npm ci
