name: Rust Build Cache

env:
  SQLX_OFFLINE: true

on:
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        description: "A list of ubuntu packages to install"
      src-dir:
        required: false
        default: src
        type: string
        description: "Path to rust source code"
      sqlx-src-dir:
        required: false
        default: postgres
        type: string
        description: "Path to sqlx source code (inside src-dir)"
      rust-version:
        required: false
        type: string
        description: "Specific rust version to use, defaults to the latest"
      custom-protoc-release-zip:
        required: false
        type: string
        description: "Custrom protoc release page zip name"
      custom-protoc-version:
        required: false
        type: string
        description: "A custom protoc version"
      build-sqlx-cache:
        required: false
        type: boolean
        default: false
        description: "Whether to build sqlx cache or not"
      postgres-version:
        required: false
        type: string
        default: postgres:15.1-alpine
        description: "Version of postgres to use in sqlx jobs"


jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: orcalabs/github-actions/disk-cleanup@master
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
          custom-protoc-version: ${{ inputs.custom-protoc-version }}
          custom-protoc-release-zip: ${{ inputs.custom-protoc-release-zip }}
      - uses: Swatinem/rust-cache@v2
        id: cache
        with:
          workspaces: ${{ inputs.src-dir }}
          shared-key: shared
      - if: steps.cache.outputs.cache-hit != 'true'
        name: build cache
        run: |
          cd ${{ inputs.src-dir }}
          cargo clippy --all-targets --all-features
          cargo doc --no-deps --document-private-items
          cargo test build

  build-sqlx-cache:
    if: ${{ inputs.build-sqlx-cache }}
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: false
      DATABASE_URL: postgres://127.0.0.1:5432?user=postgres&password=postgres
    services:
      postgres:
        image: ${{ inputs.postgres-version }}
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
          custom-protoc-version: ${{ inputs.custom-protoc-version }}
          custom-protoc-release-zip: ${{ inputs.custom-protoc-release-zip }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        id: cache
        with:
          shared-key: sqlx
          workspaces: ${{ inputs.src-dir }}
      - if: steps.cache.outputs.cache-hit != 'true'
        name: build cache
        run: |
          cd ${{ inputs.src-dir }}
          cd ${{ inputs.sqlx-src-dir }}
          cargo install sqlx-cli --no-default-features --features postgres,rustls
          sqlx migrate run
          cargo sqlx prepare --check
