name: Rust Verify

env:
  SQLX_OFFLINE: true

on:
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        description: "A list of ubuntu packages to install"
      image-build-command:
        required: false
        type: string
        description: "A command for building docker images"
      src-dir:
        required: false
        default: "src"
        type: string
        description: "Path to rust source code"
      rust-version:
        required: false
        type: string
        description: "Specific rust version to use, defaults to the latest"
      custom-protoc-release-zip:
        required: false
        type: string
        description: "Custrom protoc release page zip name"
      custom-protoc-version:
        required: false
        type: string
        description: "A custom protoc version"
      openapi-bins:
        required: false
        type: string
        description: "OpenAPI binaries to run and validate"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          rust-version: ${{ inputs.rust-version }}
      - name: cargo fmt
        run: |
          cd ${{ inputs.src-dir }}
          cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
          custom-protoc-version: ${{ inputs.custom-protoc-version }}
          custom-protoc-release-zip: ${{ inputs.custom-protoc-release-zip }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          workspaces: ${{ inputs.src-dir }}
          shared-key: shared
      - name: cargo clippy
        run: |
          cd ${{ inputs.src-dir }}
          cargo clippy --all-targets --all-features

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
          custom-protoc-version: ${{ inputs.custom-protoc-version }}
          custom-protoc-release-zip: ${{ inputs.custom-protoc-release-zip }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          workspaces: ${{ inputs.src-dir }}
          shared-key: shared
      - name: cargo doc
        run: |
          cd ${{ inputs.src-dir }}
          cargo doc --no-deps --document-private-items

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
          custom-protoc-version: ${{ inputs.custom-protoc-version }}
          custom-protoc-release-zip: ${{ inputs.custom-protoc-release-zip }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          workspaces: ${{ inputs.src-dir }}
          shared-key: shared
      - name: build images
        if: ${{ inputs.image-build-command }}
        run: ${{ inputs.image-build-command }}
      - name: cargo test
        run: |
          cd ${{ inputs.src-dir }}
          cargo test

  openapi:
    if: ${{ inputs.openapi-bins }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
          custom-protoc-version: ${{ inputs.custom-protoc-version }}
          custom-protoc-release-zip: ${{ inputs.custom-protoc-release-zip }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install swagger-cli
        run: npm install -g swagger-cli
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          workspaces: ${{ inputs.src-dir }}
          shared-key: shared
      - name: Produce openapi-spec
        run: |
          cd ${{ inputs.src-dir }}
          echo "${{ inputs.openapi-bins }}" | xargs -t -I {} sh -c 'cargo run --bin "$1" > "$1.json"' -- {}
      - name: Validate OpenAPI definition
        run: |
          cd ${{ inputs.src-dir }}
          echo "${{ inputs.openapi-bins }}" | xargs -t -I {} swagger-cli validate "{}.json"
