name: Rust Build Cache

on:
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        description: "A list of ubuntu packages to install"
      src-dir:
        required: false
        default: "src"
        type: string
        description: "Path to rust source code"
      rust-version:
        required: false
        type: string
        description: "Specific rust version to use, defaults to the latest"

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Orca Labs github actions
        uses: orcalabs/github-actions/rust-setup@master
        with:
          dependencies: ${{ inputs.dependencies }}
          cloudsmith-cargo-registry: ${{ secrets.CLOUDSMITH_CARGO_REGISTRY }}
          cloudsmith-git-api-key: ${{ secrets.CLOUDSMITH_GIT_API_KEY }}
          rust-version: ${{ inputs.rust-version }}
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: false
          shared-key: shared
      - name: build cache
        run: |
          cd ${{ inputs.src-dir }}
          cargo clippy --all-targets --all-features
          cargo doc --no-deps --document-private-items
          cargo test build
